spring:
  application:
    name: bank-api
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: Aa87654321
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 9090